description: "Install Poetry-and-NodeJS dependencies."
runs:
  using: "composite"
  steps:
    - uses: snok/install-poetry@v1
      with:
        version: 2.1.1
    - uses: actions/setup-node@v3
      with:
        node-version: 24
    - run: echo "C:\Users\runneradmin\.local\bin" >> $env:GITHUB_PATH
      shell: pwsh
      if: runner.os == 'Windows'
    - run: |
        poetry python install 3.13
        poetry install &
        npm install &
        wait
      shell: bash
