services:
  development:
    build:
      target: development
    image: ryukit/development
    volumes:
      - .:/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    command: ["-c", "bin/configure_wine && tail -f /dev/null"]
