services:
  development:
    build:
      context: .
      dockerfile: docker/development.Dockerfile
    volumes:
      - .:/workdir
    tty: true
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true

  build:
    build:
      context: .
      dockerfile: docker/build.Dockerfile
    volumes:
      - ./dist:/workdir/dist
