services:
  development:
    build:
      context: .
      dockerfile: docker/development.Dockerfile
    volumes:
      - .:/workdir
    tty: true

  build:
    build:
      context: .
      dockerfile: docker/build.Dockerfile
    volumes:
      - ./dist:/workdir/dist
