[project]
name = "ryujinxkit"
version = "2.0.0"
description = "CLI for Ryujinx (Windows) management."
authors = [
    {name = "A-2-4-8-5-10-9-7-3-6-1",email = "112730580+A-2-4-8-5-10-9-7-3-6-1@users.noreply.github.com"}
]
license = {text = "MIT"}
requires-python = ">=3.13,<3.14"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "platformdirs (>=4.3.6,<5.0.0)",
    "rich (>=13.9.4,<14.0.0)",
    "devkit @ git+https://github.com/A-2-4-8-5-10-9-7-3-6-1/python-devkit.git@v2.0.0",
    "typer-slim (>=0.15.1,<0.16.0)",
]

[tool.poetry.scripts]
ryujinxkit = "ryujinxkit.app.cli.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 79
