# =============================================================================

FROM python:3.13-bullseye AS poetry
WORKDIR /workdir

RUN pip install pipx
RUN pipx ensurepath

RUN pipx install poetry

# =============================================================================
