#!/bin/bash

# Build a Windows executable for RyuKit.
build_exe() {
    if [[ ! -z "${VIRTUAL_ENV}" ]]; then
        echo "Do not use this command within a virtual environment. Please exit first."
        return 1
    fi
    if ! wine poetry install; then
        echo "Could not begin the task. Did you run \`configure_wine\`?"
        return 1
    fi
    wine poetry run pyinstaller pyinstaller.spec
}

build_exe