-- Database setup script
CREATE TABLE IF NOT EXISTS ryujinx_saves (
  id INTEGER PRIMARY KEY,
  label TEXT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  last_used TIMESTAMP,
  size INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS ryujinx_configs (
  id INTEGER PRIMARY KEY,
  label TEXT,
  content JSON NOT NULL,
  last_used TIMESTAMP,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
