on:
  push:
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          version: 2.1.1
      - run: poetry python install 3.13
      - run: poetry install
      - run: poetry run pytest
        env:
          RYUKIT_INSTALL_URL: ${{ secrets.RYUKIT_INSTALL_URL }}
  build:
    environment: Production
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          version: 2.1.1
      - run: echo "C:\Users\runneradmin\.local\bin" >> $env:GITHUB_PATH
      - run: poetry python install 3.13
      - run: poetry install
      - run: poetry run pyinstaller pyinstaller.spec
      - uses: actions/upload-artifact@v4
        with:
          name: ryukit
          path: dist/ryukit.exe
