on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: poetry run pytest
        env:
          RYUKIT_INSTALL_URL: ${{ secrets.RYUKIT_INSTALL_URL }}
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: poetry run isort --check-only .
      - run: poetry run black --check .
      - run: npx prettier --check .
