on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  it_passes_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: poetry run pytest
        env:
          RYUKIT_INSTALL_URL: ${{ secrets.RYUKIT_INSTALL_URL }}
  its_formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: |
          poetry run isort --check-only .
          poetry run black --check .
          npx prettier --check .
