on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
