on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  test_code:
    environment: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: |
          poetry run pytest
          poetry run isort --check-only .
          poetry run black --check .
          npx prettier --check .
        env:
          RYUKIT_INSTALL_URL: ${{ secrets.RYUKIT_INSTALL_URL }}
  test_executable:
    runs-on: windows-latest
    environment: Testing
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - run: echo "$(Get-Location)\dist" >> ${env:GITHUB_PATH}
      - run: poetry run pytest
        env:
          RYUKIT_INSTALL_URL: ${{ secrets.RYUKIT_INSTALL_URL }}
