on:
  push:
    branches: [main, dev]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          version: 2.1.1
      - run: poetry python install 3.13
      - run: poetry install
      - run: poetry run pytest
        env:
          RYUKIT_INSTALL_URL: ${{ secrets.RYUKIT_INSTALL_URL }}
